### ISSUE TITLE
crashed on Android 5.0

### ISSUE THREAD

**Issue by kerberosargos** [appcelerator-modules/ti.googleanalytics#3]
I am getting this error on Android 5.0 (API 21) but that is working with 4.3 (API 18) Do you have any idea?

My Titanium SDK 5.0.0.GA

[INFO] :   APSAnalyticsService: Analytics Service Started
[WARN] :   OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xafd07ec0, error=EGL_SUCCESS
[WARN] :   TiVerify: (Timer-0) [4998,4998] Verifying module licenses...
[ERROR] :  TiApplication: (GAThread) [116,5114] Sending event: exception on thread: GAThread msg:java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.gms.analytics.service.START (has extras) }; Titanium 5.0.0,2015/09/15 23:07,ec79bc5
[ERROR] :  TiApplication: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.google.android.gms.analytics.service.START (has extras) }
[ERROR] :  TiApplication:   at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1682)
[ERROR] :  TiApplication:   at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1781)
[ERROR] :  TiApplication:   at android.app.ContextImpl.bindService(ContextImpl.java:1759)
[ERROR] :  TiApplication:   at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
[ERROR] :  TiApplication:   at com.google.analytics.tracking.android.AnalyticsGmsCoreClient.connect(AnalyticsGmsCoreClient.java:82)
[ERROR] :  TiApplication:   at com.google.analytics.tracking.android.GAServiceProxy.connectToService(GAServiceProxy.java:330)
[ERROR] :  TiApplication:   at com.google.analytics.tracking.android.GAServiceProxy.createService(GAServiceProxy.java:210)
[ERROR] :  TiApplication:   at com.google.analytics.tracking.android.GAThread.init(GAThread.java:85)
[ERROR] :  TiApplication:   at com.google.analytics.tracking.android.GAThread.run(GAThread.java:352)
[INFO] :   TiVerify: (Timer-0) [1027,6141] Succesfully verified module licenses
[ERROR] :  SQLiteLog: (5) database is locked
[ERROR] :  SQLiteDatabase: Failed to open database '/data/data/com.sizebiz.just.live.basketball/databases/appcAnalytics.db'.
[ERROR] :  SQLiteDatabase: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
[ERROR] :  SQLiteDatabase:  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1150)
[ERROR] :  SQLiteDatabase:  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
[ERROR] :  SQLiteDatabase:  at com.appcelerator.analytics.APSAnalyticsModel.deleteEvents(APSAnalyticsModel.java:107)
[ERROR] :  SQLiteDatabase:  at com.appcelerator.analytics.APSAnalyticsService$1.run(APSAnalyticsService.java:186)
[ERROR] :  SQLiteDatabase:  at java.lang.Thread.run(Thread.java:818)
[ERROR] :  APSAnalyticsModel: Error deleting events :android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
[ERROR] :  SQLiteLog: (5) database is locked
[ERROR] :  SQLiteDatabase: Failed to open database '/data/data/com.sizebiz.just.live.basketball/databases/appcAnalytics.db'.
[ERROR] :  SQLiteDatabase: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
[ERROR] :  SQLiteDatabase:  at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1150)
[ERROR] :  SQLiteDatabase:  at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
[ERROR] :  SQLiteDatabase:  at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
[ERROR] :  SQLiteDatabase:  at com.appcelerator.analytics.APSAnalyticsModel.hasEvents(APSAnalyticsModel.java:138)
[ERROR] :  SQLiteDatabase:  at com.appcelerator.analytics.APSAnalyticsService$1.run(APSAnalyticsService.java:116)
[ERROR] :  SQLiteDatabase:  at java.lang.Thread.run(Thread.java:818)
[ERROR] :  SQLiteOpenHelper: Couldn't open appcAnalytics.db for writing (will try read-only):
[ERROR] :  SQLiteOpenHelper: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:634)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:320)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:294)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
[ERROR] :  SQLiteOpenHelper:
[ERROR] :  SQLiteOpenHelper:    at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1150)
[ERROR] :  SQLiteOpenHelper:    at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:267)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
[ERROR] :  SQLiteOpenHelper:    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
[ERROR] :  SQLiteOpenHelper:    at com.appcelerator.analytics.APSAnalyticsModel.hasEvents(APSAnalyticsModel.java:138)
[ERROR] :  SQLiteOpenHelper:    at com.appcelerator.analytics.APSAnalyticsService$1.run(APSAnalyticsService.java:116)
[ERROR] :  SQLiteOpenHelper:    at java.lang.Thread.run(Thread.java:818)
[ERROR] :  APSAnalyticsModel: Error determining if there are events to send:
[ERROR] :  APSAnalyticsModel: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
[INFO] :   APSAnalyticsService: Stopping Analytics Service
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
[ERROR] :  APSAnalyticsModel:   at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:825)
[ERROR] :  APSAnalyticsModel:   at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:864)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
[ERROR] :  APSAnalyticsModel:   at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
[ERROR] :  APSAnalyticsModel:   at com.appcelerator.analytics.APSAnalyticsModel.hasEvents(APSAnalyticsModel.java:138)
[ERROR] :  APSAnalyticsModel:   at com.appcelerator.analytics.APSAnalyticsService$1.run(APSAnalyticsService.java:116)
[ERROR] :  APSAnalyticsModel:   at java.lang.Thread.run(Thread.java:818)

**Comment by MahmoudElmoghazy** [comment]
I have this problem have u fixed it or found any answer for it ?

**Comment by kerberosargos** [comment]
@MahmoudElmoghazy

You should leave only one google-play-services.jar file for your project's
all modules for fixed that.

Your google-play-services.jar file should be tiapp.xml modules nodes first
order. Other modules jar files must deleted.

For example if your google analytics module's order position is first in
tiapp.xml you leave this google-play-services.jar then you should delete
all other google-play-services.jar files for other modules.
